function [ IMG, lsf ] = getSampleImage( h, w, n )
%[ IMG, gt ] = getExample( h, w, nLines )
%   Returns an image IMG and its theoretical Linear Structure Field
%   Output is randomly generated by filling a h-by-w matrix with n lines

    mixFun = @NLVS;
    
    IMG = zeros(h,w);
    lsf = zeros(h,w);
        
    for l = 1:n
        theta = rand - 0.5;
        q = (rand - 0.5) * min(h,w);
        lsf  = drawLine(lsf,  theta*pi, q, exp(1i*theta*pi), mixFun);
        IMG = drawLine(IMG, theta*pi, q, 1, @max);
    end;
    
    lsf = lsf * exp(1i * pi/2);
    
    % Ther's some bug somewhere for getExample lsf output
    % 0 > angle(lsf) > pi   is always true
    % (i would like -pi/2 > angle(lsf) > pi/2 )
    
end

